### ISSUE TITLE
Export palettes as .txt files

### ISSUE THREAD

**Issue by FancySnacks** [A-Rave-Mistake/Color_Palette#9]
Export color palettes as .txt files that include palette name, color values and name of each color given by the user.

**Already done, adding issue for clarity and documentation.**

Commit [#2637f17](https://github.com/A-Rave-Mistake/Color_Palette/commit/2637f17887af08c7d64da9d4c3ac0729b5a8fa61)

**Comment by A-Rave-Mistake** [comment]
Closing the issue

**Comment by FancySnacks** [comment]
Closing the issue
